server {
    listen 80;
    listen [::]:80;
    server_name lionsssacademy.com.mx;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esto redirige todas las rutas fallidas al index.html de Vue
        try_files $uri $uri/ /index.html;
    }
}
